/* ============================================================
   SYDNEY MAXING — bundled catalog (offline fallback)
   The app reads window.LIVE_DATA on load. The daily agent can
   rewrite this file with fresh events (real dates + links).
   Last updated: 2026-06-11
   ============================================================ */
window.LIVE_DATA = {
  updated: "2026-06-11",
  explore: [
    { id:"twilight-at-taronga", title:"Twilight at Taronga", type:"event", cat:"Music", zone:"Taronga Zoo, Mosman",
      link:"https://twilightattaronga.org.au/", addedOn:"2026-06-11",
      desc:"Summer concert series by the harbour inside the zoo — picnic at dusk, live music (Feb–Mar 2027).",
      source:"twilightattaronga.org.au", live:true },
    { id:"field-day-sydney", title:"Field Day Festival", type:"event", cat:"Music", zone:"The Domain",
      date:"2027-01-01", link:"https://www.fielddayfestivals.com/",
      desc:"Sydney's huge New Year's Day electronic music festival in The Domain. Kick off 2027 right.",
      source:"musicfestivalwizard.com", live:true },
    { id:"sydney-festival", title:"Sydney Festival", type:"event", cat:"Festival", zone:"Citywide",
      date:"2027-01-08", link:"https://www.sydneyfestival.org.au/",
      desc:"Three weeks of theatre, music, dance and big free outdoor events all over the city (Jan 8–25).",
      source:"sydneyfestival.org.au", live:true },
    { id:"australia-day-harbourfest", title:"Australia Day Harbourfest", type:"event", cat:"Festival", zone:"Sydney Harbour",
      date:"2027-01-26", link:"https://www.sydney.com/events",
      desc:"Maritime races, aerial displays, live concerts and fireworks across the harbour.",
      source:"sydney.com", live:true },
    { id:"lunar-festival", title:"Sydney Lunar Festival", type:"event", cat:"Festival", zone:"CBD / Chinatown",
      date:"2027-02-06", link:"https://whatson.cityofsydney.nsw.gov.au/",
      desc:"Year of the Goat. Lantern installations, dragon boats and street food (kicks off Feb 6).",
      source:"cityofsydney", live:true },
    { id:"mardi-gras-parade", title:"Mardi Gras Parade", type:"event", cat:"Festival", zone:"Oxford St",
      date:"2027-03-06", link:"https://www.mardigras.org.au/event/parade/",
      desc:"One of the world's biggest LGBTQ+ celebrations. The parade lights up Oxford St on Sat Mar 6.",
      source:"mardigras.org.au", live:true },
    { id:"royal-easter-show", title:"Sydney Royal Easter Show", type:"event", cat:"Festival", zone:"Olympic Park",
      date:"2027-03-19", link:"https://www.eastershow.com.au/",
      desc:"Carnival rides, showbags, animals and fireworks (Mar 19–30). A proper Aussie tradition.",
      source:"eastershow.com.au", live:true },
    { id:"vivid-sydney", title:"Vivid Sydney", type:"event", cat:"Festival", zone:"Citywide",
      date:"2027-05-23", link:"https://www.vividsydney.com/",
      desc:"The harbour and city light up nightly — light art, music and food (May 23–Jun 14).",
      source:"vividsydney.com", live:true },
    { id:"bondi-coogee-walk", title:"Bondi to Coogee Coastal Walk", type:"sight", cat:"Beach", zone:"Bondi",
      link:"https://www.google.com/maps/search/?api=1&query=Bondi+to+Coogee+Coastal+Walk",
      desc:"6km of clifftops and beaches — the most iconic walk in Sydney." },
    { id:"opera-house", title:"Sydney Opera House", type:"sight", cat:"Culture", zone:"CBD",
      link:"https://www.sydneyoperahouse.com/",
      desc:"Catch a show or do the inside tour of the building everyone knows." },
    { id:"blue-mountains", title:"Blue Mountains — Three Sisters", type:"sight", cat:"Nature", zone:"Katoomba",
      link:"https://www.google.com/maps/search/?api=1&query=Three+Sisters+Blue+Mountains",
      desc:"Day trip from the city — lookouts, waterfalls and bushwalks." },
    { id:"manly-ferry", title:"Manly Ferry at sunset", type:"sight", cat:"Beach", zone:"Manly",
      link:"https://www.google.com/maps/search/?api=1&query=Manly+Ferry+Sydney",
      desc:"The iconic ferry across the harbour — go at golden hour." },
    { id:"featherdale", title:"Koalas & kangaroos (Featherdale)", type:"sight", cat:"Nature", zone:"Doonside",
      link:"https://www.featherdale.com.au/",
      desc:"Feed kangaroos and get a photo with a koala." }
  ],
  eats: [
    { id:"porteno", title:"Porteño", type:"restaurant", cat:"Dinner", zone:"Surry Hills",
      link:"https://www.google.com/maps/search/?api=1&query=Porteno+Surry+Hills+Sydney",
      desc:"Argentinian flame-grilled steak — ranked among the world's best steak restaurants.", source:"gourmettraveller" },
    { id:"pellegrino-2000", title:"Pellegrino 2000", type:"restaurant", cat:"Dinner", zone:"Surry Hills",
      link:"https://www.google.com/maps/search/?api=1&query=Pellegrino+2000+Surry+Hills",
      desc:"Roman/Florentine trattoria vibes — handmade tortellini, pappardelle bolognese.", source:"gourmettraveller" },
    { id:"bessies", title:"Bessie's", type:"bar", cat:"Bar", zone:"Surry Hills",
      link:"https://www.google.com/maps/search/?api=1&query=Bessies+wine+bar+Surry+Hills",
      desc:"Small plates + big vibe — the quintessential Surry Hills wine bar of the moment.", source:"gourmettraveller" },
    { id:"osteria-mucca", title:"Osteria Mucca", type:"restaurant", cat:"Dinner", zone:"Newtown",
      link:"https://www.google.com/maps/search/?api=1&query=Osteria+Mucca+Newtown",
      desc:"50-seat old-school Italian trattoria, nose-to-tail cooking and lots of pasta.", source:"gourmettraveller" },
    { id:"marys", title:"Mary's", type:"restaurant", cat:"Casual", zone:"Newtown",
      link:"https://www.google.com/maps/search/?api=1&query=Marys+Newtown+Sydney",
      desc:"The best burgers in Sydney, rock'n'roll basement vibe." },
    { id:"bills-surry", title:"Bills (ricotta hotcakes)", type:"cafe", cat:"Brunch", zone:"Surry Hills",
      link:"https://www.google.com/maps/search/?api=1&query=Bills+Surry+Hills",
      desc:"The most famous brunch in Sydney — those ricotta hotcakes." },
    { id:"fish-market", title:"Sydney Fish Market", type:"market", cat:"Market", zone:"Pyrmont",
      link:"https://www.sydneyfishmarket.com.au/",
      desc:"Ultra-fresh seafood — go early and eat by the water." },
    { id:"paddington-markets", title:"Paddington Markets", type:"shop", cat:"Shopping", zone:"Paddington",
      link:"https://www.paddingtonmarkets.com.au/",
      desc:"Saturdays — local designers and vintage finds." }
  ],
  trips: [
    { id:"queenstown-nz", title:"Queenstown, New Zealand", type:"country", cat:"Neighbour", zone:"South Island",
      link:"https://www.google.com/flights?hl=en#flt=SYD.ZQN",
      desc:"Bungee, glaciers and movie-set scenery. ~3h flight from Sydney." },
    { id:"bali", title:"Bali, Indonesia", type:"country", cat:"Neighbour", zone:"Indonesia",
      link:"https://www.google.com/flights?hl=en#flt=SYD.DPS",
      desc:"~6h flight, cheap from Sydney. Beaches, temples, nightlife.", live:true },
    { id:"byron-bay", title:"Byron Bay roadtrip", type:"roadtrip", cat:"Roadtrip", zone:"NSW North Coast",
      link:"https://www.google.com/maps/search/?api=1&query=Byron+Bay",
      desc:"Surf, hippie-chic, lighthouse at sunrise." },
    { id:"gold-coast", title:"Gold Coast weekend", type:"weekend", cat:"Weekend", zone:"Queensland",
      link:"https://www.google.com/flights?hl=en#flt=SYD.OOL",
      desc:"Beaches and theme parks — easy quick flight." },
    { id:"fiji", title:"Fiji", type:"country", cat:"Island", zone:"Pacific",
      link:"https://www.google.com/flights?hl=en#flt=SYD.NAN",
      desc:"Island paradise, ~4h from Sydney." },
    { id:"hobart-tas", title:"Hobart & MONA, Tasmania", type:"weekend", cat:"Weekend", zone:"Tasmania",
      link:"https://www.google.com/flights?hl=en#flt=SYD.HBA",
      desc:"MONA museum, Salamanca markets, wild nature." }
  ]
};
